server:
    port: 8080


spring:
    webflux:
        base-path: ${CONTEXT_PATH}
    application:
        name : java-reactive
    config:
        import: optional:file:.env[.properties]
    r2dbc:
        url: r2dbc:postgresql://${R2DBC_HOST}:5432/${R2DBC_DB}
        username: ${R2DBC_USERNAME}
        password: ${R2DBC_PASSWORD}
